### ISSUE TITLE
ID duplicated in Database

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/goMeGo#6]
The player KEY is duplicated as ID in the database.

**Comment by johnRedden** [comment]
userMarker array used in mapping uses this property... too hard to change without a complete refactor.

**Comment by pgonzbecer** [comment]
not sure if this is a problem? We need to store the ID so we can access front end stuff regarding the id but we also need to use the ID to upload to the database. I cant see a work around to this

**Comment by johnRedden** [comment]
Yeah, the work around is a complete refactor!  I say we leave it.
